<?php

$locale = !empty($params['locale']) ? $params['locale'] : wa()->getLocale();

return array(
    'sections' => array(
        'styles' => array(
            'title'      => _wp('Styles'),
            'autoApply'  => $this->getSettings('autoApply'),
            'compatible' => $this->getSettings('compatible'),
            // locale strings
            'messages'   => customizerHelper::getLocaleMessages(array($this->app_id, $this->id), $locale),
            // themes & subthemes
            'themes'     => $this->getThemes(),
            // general group
            'general'    => array(
                'global',
                'theme',
                'inverse',
                'primary'
            ),
            // ignored vars
            'ignore' => array(
                '@deprecated',
                '@breakpoint-*-max',
                '@internal*',
                '@heading-primary-*',
                '@heading-hero-*',
                // '@inverse-global-color-mode',
            ),
            'groups' => array(
                'global' => array(
                    'typography'  => array(
                        '@global-(?!primary|secondary|tertiary)*font-*',
                        '@global-(?!primary|secondary|tertiary)*line-height',
                    ),
                    'primary'     => '@global-primary-(?!color|background)*',
                    'secondary'   => '@global-secondary-(?!color|background)*',
                    'tertiary'    => '@global-tertiary-*',
                    'colors'      => '*-color',
                    'backgrounds' => '*-background',
                    'borders'     => '*-border*',
                    'box shadows' => '*-box-shadow*',
                    'spacings'    => array(
                        '*-margin',
                        '*-gutter',
                    ),
                    'controls'    => '*-control-*',
                    'z index'     => '*-z-index',
                    'breakpoints' => '@breakpoint-*',
                ),
                'theme' => array(
                    'page' => '@theme-page-*',
                    'page container' => '@theme-page-container-*',
                    'toolbar' => '@theme-toolbar-*',
                    'headerbar top' => '@theme-headerbar-top-*',
                    'headerbar bottom' => '@theme-headerbar-bottom-*',
                    'headerbar stacked' => '@theme-headerbar-stacked-*',
                    'sidebar' => '@theme-sidebar-*',
                    'section title' => '@section-title-*',
                    'mask default' => '@theme-mask-default-*',
                    'box decoration' => '@theme-box-decoration-*',
                    'box decoration default' => '@theme-box-decoration-default-*',
                    'box decoration primary' => '@theme-box-decoration-primary-*',
                    'box decoration secondary' => '@theme-box-decoration-secondary-*',
                ),
                'accordion' => array(
                    'item'    => '@accordion-item-*',
                    'icon'    => '@accordion-icon-*',
                    'title'   => '@accordion-title-*',
                    'content' => '@accordion-content-*',
                ),
                'alert' => array(
                    'primary' => '@alert-primary-*',
                    'success' => '@alert-success-*',
                    'warning' => '@alert-warning-*',
                    'danger'  => '@alert-danger-*',
                    'close'   => '@alert-close-*',
                ),
                'animation' => array(
                    'slide' => '@animation-slide-*',
                ),
                'article' => array(
                    'title'     => '@article-title-*',
                    'meta'      => '@article-meta-*',
                    'meta link' => '@article-meta-link-*',
                ),
                'background' => array(
                    'default'   => '@background-default-*',
                    'muted'     => '@background-muted-*',
                    'primary'   => '@background-primary-*',
                    'secondary' => '@background-secondary-*',
                    'danger'    => '@background-danger-*',
                ),
                'badge' => array(
                    'default'    => '@badge-default-*',
                    'muted'      => '@badge-muted-*',
                    'primary'    => '@badge-primary-*',
                    'secondary'  => '@badge-secondary-*',
                    'bestseller' => '@badge-bestseller-*',
                    'low price'  => '@badge-low-price-*',
                    'new'        => '@badge-new-*',
                    'success'    => '@badge-success-*',
                    'warning'    => '@badge-warning-*',
                    'danger'     => '@badge-danger-*',
                    'large'      => '@badge-large-*',
                ),
                'bar' => array(
                    'nav'           => '@bar-nav-*',
                    'nav item'      => '@bar-nav-item-*',
                    'item'          => '@bar-item-*',
                    'toggle'        => '@bar-toggle-*',
                    'title'         => '@bar-title-*',
                    'subnav'        => '@bar-subnav-*',
                    'link'          => '@bar-link-*',
                    'default'       => '@bar-default-*',
                    'muted'         => '@bar-muted-*',
                    'primary'       => '@bar-primary-*',
                    'secondary'     => '@bar-secondary-*',
                    'overlay light' => '@bar-overlay-light-*',
                    'overlay dark'  => '@bar-overlay-dark-*',
                    'small'         => '@bar-small-*',
                    'medium'        => '@bar-medium-*',
                    'large'         => '@bar-large-*',
                ),
                'base' => array(
                    'body' => '@base-body-*',
                    'link' => '@base-link-*',
                    'strong' => '@base-strong-*',
                    'code' => '@base-code-*',
                    'em' => '@base-em-*',
                    'ins' => '@base-ins-*',
                    'mark' => '@base-mark-*',
                    'quote' => '@base-quote-*',
                    'small' => '@base-small-*',
                    'margin' => '@base-margin-*',
                    'heading' => '@base-heading-*',
                    'h1' => '@base-h1-*',
                    'h2' => '@base-h2-*',
                    'h3' => '@base-h3-*',
                    'h4' => '@base-h4-*',
                    'h5' => '@base-h5-*',
                    'h6' => '@base-h6-*',
                    'list' => '@base-list-*',
                    'hr' => '@base-hr-*',
                    'blockquote' => '@base-blockquote-*',
                    'blockquote footer' => '@base-blockquote-footer-*',
                    'pre' => '@base-pre-*',
                    'selection' => '@base-selection-*',
                ),
                'border' => array(
                    'default'   => '@border-default-*',
                    'muted'     => '@border-muted-*',
                    'primary'   => '@border-primary-*',
                    'secondary' => '@border-secondary-*',
                ),
                'breadcrumb' => array(
                    'item'    => '@breadcrumb-item-*',
                    'divider' => '@breadcrumb-divider*',
                ),
                'button' => array(
                    'default'   => '@button-default-*',
                    'primary'   => '@button-primary-*',
                    'secondary' => '@button-secondary-*',
                    'danger'    => '@button-danger-*',
                    'feature'   => '@button-feature-*',
                    'color'     => '@button-color-*',
                    'loading'   => '@button-loading-*',
                    'disabled'  => '@button-disabled-*',
                    'text'      => array(
                        '@button-text-mode',
                        '@button-text-(?!transform)*',
                    ),
                    'link'      => '@button-link-*',
                    'small'     => '@button-small-*',
                    'large'     => '@button-large-*',
                ),
                'card' => array(
                    'body'            => '@card-body-*',
                    'header'          => '@card-header-*',
                    'footer'          => '@card-footer-*',
                    'title'           => '@card-title-*',
                    'badge'           => '@card-badge-*',
                    'hover'           => '@card-hover*',
                    'default'         => '@card-default-*',
                    'default title'   => '@card-default-title-*',
                    'default header'  => '@card-default-header-*',
                    'default footer'  => '@card-default-footer-*',
                    'muted'           => '@card-muted-*',
                    'muted title'     => '@card-muted-title-*',
                    'primary'         => '@card-primary-*',
                    'primary title'   => '@card-primary-title-*',
                    'secondary'       => '@card-secondary-*',
                    'secondary title' => '@card-secondary-title-*',
                    'sidebar'         => '@card-sidebar-*',
                    'sidebar title'   => '@card-sidebar-title-*',
                    'product'         => '@card-product-*',
                    'product title'   => '@card-product-title-*',
                    'small'           => '@card-small-*',
                    'large'           => '@card-large-*',
                ),
                'column' => array(
                    'divider' => '@column-divider-*',
                ),
                'comment' => array(
                    'header'  => '@comment-header-*',
                    'title'   => '@comment-title-*',
                    'meta'    => '@comment-meta-*',
                    'list'    => '@comment-list-*',
                    'primary' => '@comment-primary-*',
                ),
                'container' => array(
                    'xsmall' => '@container-xsmall-*',
                    'small'  => '@container-small-*',
                    'large'  => '@container-large-*',
                ),
                'countdown' => array(
                    'item'      => '@countdown-item-*',
                    'number'    => '@countdown-number-*',
                    'separator' => '@countdown-separator-*',
                    'label'     => '@countdown-label-*',
                    'small'     => '@countdown-small-*',
                    'large'     => '@countdown-large-*',
                ),
                'description list' => array(
                    'term'        => '@description-list-term-*',
                    'description' => '@description-list-description-*',
                    'divider'     => '@description-list-divider-*',
                ),
                'divider' => array(
                    'divider icon'     => '@divider-icon-*',
                    'divider small'    => '@divider-small-*',
                    'divider vertical' => '@divider-vertical-*',
                ),
                'dotnav' => array(
                    'item' => '@dotnav-item-*',
                ),
                'dropdown' => array(
                    'nav' => '@dropdown-nav-(?!item|header|divider|sublist)*',
                    'nav item'    => '@dropdown-nav-item-*',
                    'nav header'  => '@dropdown-nav-header-*',
                    'nav divider' => '@dropdown-nav-divider-*',
                    'nav sublist' => '@dropdown-nav-sublist-*',
                ),
                'form' => array(
                    'danger'     => '@form-danger-*',
                    'success'    => '@form-success-*',
                    'blank'      => '@form-blank-*',
                    'select'     => '@form-select-*',
                    'range'      => '@form-range-*',
                    'small'      => '@form-small-*',
                    'large'      => '@form-large-*',
                    'width'      => '@form-width-*',
                    'radio'      => '@form-radio-*',
                    'legend'     => '@form-legend-*',
                    'label'      => '@form-label-*',
                    'stacked'    => '@form-stacked-*',
                    'horizontal' => '@form-horizontal-*',
                    'icon'       => '@form-icon-*',
                    'slider'     => '@form-slider-control-*',
                ),
                'grid' => array(
                    'small' => '@grid-small-*',
                    'medium' => '@grid-medium-*',
                    'large' => '@grid-large-*',
                    'divider' => '@grid-divider-*',
                ),
                'heading' => array(
                    'small' => '@heading-small-*',
                    'medium' => '@heading-medium-*',
                    'large' => '@heading-large-*',
                    'xlarge' => '@heading-xlarge-*',
                    '2xlarge' => '@heading-2xlarge-*',
                    'divider' => '@heading-divider-*',
                    'bullet' => '@heading-bullet-*',
                    'line' => '@heading-line-*',
                ),
                'icon' => array(
                    'link' => '@icon-link-*',
                    'button' => '@icon-button-*',
                    'image' => '@icon-image-*',
                ),
                'iconnav' => array(
                    'item' => '@iconnav-item-*',
                ),
                'inverse' => array(
                    'global' => array(
                        '@inverse-global-color-mode',
                        '@inverse-global-*',
                        '@inverse-small-box-shadow',
                        '@inverse-medium-box-shadow',
                        '@inverse-large-box-shadow',
                        '@inverse-xlarge-box-shadow',
                    ),
                    'theme' => array(
                        '@inverse-section-title-*',
                        '@inverse-theme-box-decoration-default-*',
                        '@inverse-theme-box-decoration-primary-*',
                        '@inverse-theme-box-decoration-secondary-*',
                    ),
                    'accordion' => '@inverse-accordion-*',
                    'article' => '@inverse-article-*',
                    'badge' => '@inverse-badge-*',
                    'bar' => '@inverse-bar-*',
                    'base' => '@inverse-base-*',
                    'border' => '@inverse-border-*',
                    'breadcrumb' => '@inverse-breadcrumb-*',
                    'button default' => '@inverse-button-default-*',
                    'button primary' => '@inverse-button-primary-*',
                    'button secondary' => '@inverse-button-secondary-*',
                    'button danger' => '@inverse-button-danger-*',
                    'button feature' => '@inverse-button-feature-*',
                    'button color' => '@inverse-button-color-*',
                    'button loading' => '@inverse-button-loading-*',
                    'button disabled' => '@inverse-button-disabled-*',
                    'button text' => '@inverse-button-text-(?!transform)*',
                    'button link' => '@inverse-button-link-*',
                    'card' => '@inverse-card-*',
                    'close' => '@inverse-close-*',
                    'column' => '@inverse-column-*',
                    'comment' => '@inverse-comment-*',
                    'countdown' => '@inverse-countdown-*',
                    'description list' => '@inverse-description-list-*',
                    'divider' => '@inverse-divider-*',
                    'dotnav' => '@inverse-dotnav-*',
                    'form' => '@inverse-form-*',
                    'form danger' => '@inverse-form-danger-*',
                    'form success' => '@inverse-form-success-*',
                    'form blank' => '@inverse-form-blank-*',
                    'form select' => '@inverse-form-select-*',
                    'form radio' => '@inverse-form-radio-*',
                    'form legend' => '@inverse-form-legend-*',
                    'form label' => '@inverse-form-label-*',
                    'form icon' => '@inverse-form-icon-*',
                    'grid divider' => '@inverse-grid-divider-*',
                    'heading' => '@inverse-heading-*',
                    'icon link' => '@inverse-icon-link-*',
                    'icon button' => '@inverse-icon-button-*',
                    'icon rating' => '@inverse-icon-rating-*',
                    'iconnav' => '@inverse-iconnav-*',
                    'label' => '@inverse-label-*',
                    'leader' => '@inverse-leader-*',
                    'link' => '@inverse-link-*',
                    'list' => '@inverse-list-*',
                    'marker' => '@inverse-marker-*',
                    'menu' => '@inverse-menu-*',
                    'nav' => '@inverse-nav-*',
                    'nav default' => '@inverse-nav-default-*',
                    'nav primary' => '@inverse-nav-primary-*',
                    'navbar' => '@inverse-navbar-*',
                    'navbar nav item' => '@inverse-navbar-nav-item-*',
                    'navbar nav item line' => '@inverse-navbar-nav-item-line-*',
                    'pagination' => '@inverse-pagination-*',
                    'placeholder' => '@inverse-placeholder-*',
                    'product' => '@inverse-product-*',
                    'search' => '@inverse-search-*',
                    'search default' => '@inverse-search-default-*',
                    'search navbar' => '@inverse-search-navbar-*',
                    'search large' => '@inverse-search-large-*',
                    'search toggle' => '@inverse-search-toggle-*',
                    'slidenav' => '@inverse-slidenav-*',
                    'subnav' => '@inverse-subnav-*',
                    'subnav divider' => '@inverse-subnav-divider-*',
                    'subnav pill' => '@inverse-subnav-pill-*',
                    'tab' => '@inverse-tab-*',
                    'table' => '@inverse-table-*',
                    'text' => '@inverse-text-*',
                    'thumbnav' => '@inverse-thumbnav-*',
                    'totop' => '@inverse-totop-*',
                    'utility' => array(
                        '@inverse-dropcap-*',
                        '@inverse-logo-*',
                        '@inverse-box-shadow-bottom-background',
                        '@inverse-panel-scrollable-*',
                        '@inverse-dragover-box-*',
                        '@inverse-panel-box-*',
                    ),
                ),
                'label' => array(
                    'success' => '@label-success-*',
                    'warning' => '@label-warning-*',
                    'danger' => '@label-danger-*',
                ),
                'lightbox' => array(
                    'item' => '@lightbox-item-*',
                    'toolbar' => '@lightbox-toolbar-*',
                    'toolbar icon' => '@lightbox-toolbar-icon-*',
                    'button' => '@lightbox-button-*',
                ),
                'link' => array(
                    'muted' => '@link-muted-*',
                    'text' => '@link-text-*',
                    'heading' => '@link-heading-*',
                ),
                'list' => array(
                    'divider' => '@list-divider-*',
                    'striped' => '@list-striped-*',
                    'bullet' => '@list-bullet-*',
                    'large' => '@list-large-*',
                    'large divider' => '@list-large-divider-*',
                    'large striped' => '@list-large-striped-*',
                ),
                'margin' => array(
                    'xsmall' => '@margin-xsmall-*',
                    'small' => '@margin-small-*',
                    'medium' => '@margin-medium-*',
                    'large' => '@margin-large-*',
                    'xlarge' => '@margin-xlarge-*',
                ),
                'menu'  => array(
                    'nav'                   => '@menu-nav-*',
                    'dropdown'              => '@menu-dropdown-(?!nav)*',
                    'dropdown nav'          => '@menu-dropdown-nav-(?!default|icons)*',
                    'dropdown nav default'  => '@menu-dropdown-nav-default-*',
                    'dropdown nav icons'    => '@menu-dropdown-nav-icons-*',
                    'dropbar'               => '@menu-dropbar-(?!nav)*',
                    'dropbar nav'           => '@menu-dropbar-nav-(?!default|icons|primary|secondary|banner)*',
                    'dropbar nav default'   => '@menu-dropbar-nav-default-*',
                    'dropbar nav icons'     => '@menu-dropbar-nav-icons-*',
                    'dropbar nav primary'   => '@menu-dropbar-nav-primary-*',
                    'dropbar nav secondary' => '@menu-dropbar-nav-secondary-*',
                    'dropbar nav banner'    => '@menu-dropbar-nav-banner-*',
                    'accordion nav'         => '@menu-accordion-nav-(?!default|icons)*',
                    'accordion nav default' => '@menu-accordion-nav-default-*',
                    'accordion nav icons'   => '@menu-accordion-nav-icons-*',
                ),
                'modal' => array(
                    'dialog' => '@modal-dialog-*',
                    'container' => '@modal-container-*',
                    'body' => '@modal-body-*',
                    'header' => '@modal-header-*',
                    'footer' => '@modal-footer-*',
                    'title' => '@modal-title-*',
                    'close' => '@modal-close-*',
                    'close outside' => '@modal-close-outside-*',
                ),
                'nav' => array(
                    'item' => '@nav-item-*',
                    'sublist' => '@nav-sublist-*',
                    'parent icon' => '@nav-parent-icon-*',
                    'header' => '@nav-header-*',
                    'divider' => '@nav-divider-*',
                    'default' => '@nav-default-*',
                    'default item' => '@nav-default-item-*',
                    'default header' => '@nav-default-header-*',
                    'default divider' => '@nav-default-divider-*',
                    'default sublist' => '@nav-default-sublist-*',
                    'primary' => '@nav-primary-*',
                    'primary item' => '@nav-primary-item-*',
                    'primary header' => '@nav-primary-header-*',
                    'primary divider' => '@nav-primary-divider-*',
                    'primary sublist' => '@nav-primary-sublist-*',
                ),
                'navbar' => array(
                    'group' => '@navbar-group-*',
                    'nav' => '@navbar-nav-*',
                    'nav item' => '@navbar-nav-item-*',
                    'nav item line' => array(
                        '@navbar-nav-item-line-mode',
                        '@navbar-nav-item-line-position-mode',
                        '@navbar-nav-item-line-slide-mode',
                        '@navbar-nav-item-line-*',
                    ),
                    'item' => '@navbar-item-*',
                    'toggle' => '@navbar-toggle-*',
                    'subtitle' => '@navbar-subtitle-*',
                    'primary' => '@navbar-primary-*',
                    'sticky' => '@navbar-sticky-*',
                    'dropdown' => '@navbar-dropdown-*',
                    'dropdown grid' => '@navbar-dropdown-grid-*',
                    'dropdown nav' => '@navbar-dropdown-nav-*',
                    'dropdown nav item' => '@navbar-dropdown-nav-item-*',
                    'dropdown nav header' => '@navbar-dropdown-nav-header-*',
                    'dropdown nav divider' => '@navbar-dropdown-nav-divider-*',
                    'dropdown nav sublist' => '@navbar-dropdown-nav-sublist-*',
                    'dropbar' => '@navbar-dropbar-*',
                ),
                'notification' => array(
                    'message' => '@notification-message-(?!primary|success|warning|danger)*',
                    'close' => '@notification-close-*',
                    'message primary' => '@notification-message-primary-*',
                    'message success' => '@notification-message-success-*',
                    'message warning' => '@notification-message-warning-*',
                    'message danger' => '@notification-message-danger-*',
                ),
                'offcanvas' => array(
                    'bar' => '@offcanvas-bar-*',
                    'close' => '@offcanvas-close-*',
                    'overlay' => '@offcanvas-overlay-*',
                ),
                'overlay' => array(
                    'default' => '@overlay-default-*',
                    'primary' => '@overlay-primary-*',
                ),
                'padding' => array(
                    'xsmall'  => '@padding-xsmall-*',
                    'small'   => '@padding-small-*',
                    'medium'  => '@padding-medium-*',
                    'large'   => '@padding-large-*',
                    'xlarge'  => '@padding-xlarge-*',
                ),
                'pagination' => array(
                    'item' => '@pagination-item-*',
                ),
                'primary' => array(
                    'global' => array(
                        '@primary-global-color-mode',
                        '@primary-global-*',
                        '@primary-small-box-shadow',
                        '@primary-medium-box-shadow',
                        '@primary-large-box-shadow',
                        '@primary-xlarge-box-shadow',
                    ),
                    'theme' => array(
                        '@primary-section-title-*',
                        '@primary-theme-box-decoration-default-*',
                        '@primary-theme-box-decoration-primary-*',
                        '@primary-theme-box-decoration-secondary-*',
                    ),
                    'accordion' => '@primary-accordion-*',
                    'article' => '@primary-article-*',
                    'badge' => '@primary-badge-*',
                    'bar' => '@primary-bar-*',
                    'base' => '@primary-base-*',
                    'border' => '@primary-border-*',
                    'breadcrumb' => '@primary-breadcrumb-*',
                    'button default' => '@primary-button-default-*',
                    'button primary' => '@primary-button-primary-*',
                    'button secondary' => '@primary-button-secondary-*',
                    'button danger' => '@primary-button-danger-*',
                    'button feature' => '@primary-button-feature-*',
                    'button color' => '@primary-button-color-*',
                    'button loading' => '@primary-button-loading-*',
                    'button disabled' => '@primary-button-disabled-*',
                    'button text' => '@primary-button-text-(?!transform)*',
                    'button link' => '@primary-button-link-*',
                    'card' => '@primary-card-*',
                    'close' => '@primary-close-*',
                    'column' => '@primary-column-*',
                    'comment' => '@primary-comment-*',
                    'countdown' => '@primary-countdown-*',
                    'description list' => '@primary-description-list-*',
                    'divider' => '@primary-divider-*',
                    'dotnav' => '@primary-dotnav-*',
                    'form' => '@primary-form-*',
                    'form danger' => '@primary-form-danger-*',
                    'form success' => '@primary-form-success-*',
                    'form blank' => '@primary-form-blank-*',
                    'form select' => '@primary-form-select-*',
                    'form radio' => '@primary-form-radio-*',
                    'form legend' => '@primary-form-legend-*',
                    'form label' => '@primary-form-label-*',
                    'form icon' => '@primary-form-icon-*',
                    'grid divider' => '@primary-grid-divider-*',
                    'heading' => '@primary-heading-*',
                    'icon link' => '@primary-icon-link-*',
                    'icon button' => '@primary-icon-button-*',
                    'icon rating' => '@primary-icon-rating-*',
                    'iconnav' => '@primary-iconnav-*',
                    'label' => '@primary-label-*',
                    'leader' => '@primary-leader-*',
                    'link' => '@primary-link-*',
                    'list' => '@primary-list-*',
                    'marker' => '@primary-marker-*',
                    'menu' => '@primary-menu-*',
                    'nav' => '@primary-nav-*',
                    'nav default' => '@primary-nav-default-*',
                    'nav primary' => '@primary-nav-primary-*',
                    'navbar' => '@primary-navbar-*',
                    'navbar nav item' => '@primary-navbar-nav-item-*',
                    'navbar nav item line' => '@primary-navbar-nav-item-line-*',
                    'pagination' => '@primary-pagination-*',
                    'placeholder' => '@primary-placeholder-*',
                    'product' => '@primary-product-*',
                    'search' => '@primary-search-*',
                    'search default' => '@primary-search-default-*',
                    'search navbar' => '@primary-search-navbar-*',
                    'search large' => '@primary-search-large-*',
                    'search toggle' => '@primary-search-toggle-*',
                    'slidenav' => '@primary-slidenav-*',
                    'subnav' => '@primary-subnav-*',
                    'subnav divider' => '@primary-subnav-divider-*',
                    'subnav pill' => '@primary-subnav-pill-*',
                    'tab' => '@primary-tab-*',
                    'table' => '@primary-table-*',
                    'text' => '@primary-text-*',
                    'thumbnav' => '@primary-thumbnav-*',
                    'totop' => '@primary-totop-*',
                    'utility' => array(
                        '@primary-dropcap-*',
                        '@primary-logo-*',
                        '@primary-box-shadow-bottom-background',
                        '@primary-panel-scrollable-*',
                        '@primary-dragover-box-*',
                        '@primary-panel-box-*',
                    ),
                ),
                'product' => array(
                    'price'         => '@product-price-(?!compare)*',
                    'price compare' => '@product-price-compare-*',
                    'unavailable'   => '@product-unavailable-*',
                    'compare'       => '@product-compare-*',
                    'favorite'      => '@product-favorite-*',
                ),
                'progress' => array(
                    'bar' => '@progress-bar-*',
                ),
                'search' => array(
                    'default' => '@search-default-*',
                    'navbar' => '@search-navbar-*',
                    'large' => '@search-large-*',
                    'toggle' => '@search-toggle-*',
                ),
                'section' => array(
                    'default' => '@section-default-*',
                    'muted' => '@section-muted-*',
                    'primary' => '@section-primary-*',
                    'secondary' => '@section-secondary-*',
                    'xsmall' => '@section-xsmall-*',
                    'small' => '@section-small-*',
                    'large' => '@section-large-*',
                    'xlarge' => '@section-xlarge-*'
                ),
                'slidenav' => array(
                    'large' => '@slidenav-large-*',
                ),
                'subnav' => array(
                    'item' => '@subnav-item-*',
                    'divider' => '@subnav-divider-*',
                    'pill' => '@subnav-pill-*',
                    'pill item' => '@subnav-pill-item-*',
                ),
                'tab' => array(
                    'item' => '@tab-item-*',
                    'vertical' => '@tab-vertical-*',
                    'vertical item' => '@tab-vertical-item-*',
                ),
                'table' => array(
                    'cell' => '@table-cell-*',
                    'header cell' => '@table-header-cell-*',
                    'footer' => '@table-footer-*',
                    'caption' => '@table-caption-*',
                    'row' => '@table-row-*',
                    'divider' => '@table-divider-*',
                    'striped' => '@table-striped-*',
                    'hover' => '@table-hover-*',
                    'small' => '@table-small-*',
                    'large' => '@table-large-*',
                    'expand' => '@table-expand-*',
                ),
                'text' => array(
                    'lead' => '@text-lead-*',
                    'meta' => '@text-meta-*',
                    'small' => '@text-small-*',
                    'large' => '@text-large-*',
                ),
                'thumbnav' => array(
                    'item' => '@thumbnav-item-*',
                ),
                'tile' => array(
                    'default' => '@tile-default-*',
                    'muted' => '@tile-muted-*',
                    'primary' => '@tile-primary-*',
                    'secondary' => '@tile-secondary-*',
                    'xsmall' => '@tile-xsmall-*',
                    'small' => '@tile-small-*',
                    'large' => '@tile-large-*',
                    'xlarge' => '@tile-xlarge-*',
                ),
                'transition' => array(
                    'slide' => '@transition-slide-*',
                ),
                'utility' => array(
                    'panel scrollable' => '@panel-scrollable-*',
                    'border rounded' => '@border-rounded-*',
                    'box shadow' => '@box-shadow-*',
                    'box shadow bottom' => '@box-shadow-bottom-*',
                    'dropcap' => '@dropcap-*',
                    'logo' => '@logo-*',
                    'dragover' => '@dragover-*',
                ),
            ),
            // types fields
            'types' => array(
                array(
                    'type' => 'color',
                    'vars' => array(
                        '*-color',
                        // '*-border',
                        // '*-border-top',
                        // '*-border-bottom',
                        // '*-border-left',
                        // '*-border-right',
                        // '*-background',
                        // '@global*-background',
                    ),
                ),
                array(
                    'type' => 'border',
                    'vars' => array(
                        '*-border',
                        '*-border-top',
                        '*-border-bottom',
                        '*-border-left',
                        '*-border-right',
                    ),
                ),
                array(
                    'type' => 'background',
                    'vars' => array(
                        '*-background',
                    ),
                ),
                array(
                    'type' => 'boxshadow',
                    'vars' => array(
                        '*-box-shadow',
                        '*-box-shadow-vertical',
                    ),
                ),
                array(
                    'type'  => 'textshadow',
                    'vars'  => '*-text-shadow',
                    'attrs' => array(
                        'disableSpreadRadius' => true,
                        'disableInset'        => true,
                    ),
                ),
                array(
                    'type' => 'select-custom',
                    'vars' => array(
                        '*-border-style',
                        '@border*style',
                    ),
                    'options' => array(
                        'Solid'  => 'solid',
                        'Dashed' => 'dashed',
                        'Dotted' => 'dotted',
                        'None'   => 'none',
                    ),
                ),
                array(
                    'type' => 'font',
                    'vars' => '*-font-family',
                ),
                /*
                array(
                    'type' => 'select-custom',
                    'vars' => '*-font-family',
                    'options' => array(
                        'Default System Font' => '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
                        'Consolas/Monaco'     => 'Consolas, monaco, monospace',
                        'Georgia'             => 'Georgia, "Times New Roman", Times, serif',
                        'Helvetica/Arial'     => '"Helvetica Neue", Helvetica, Arial, sans-serif',
                        'Lucida'              => '"Lucida Grande", "Lucida Sans Unicode", Verdana, sans-serif',
                        'Times New Roman'     => '"Times New Roman", Times, serif',
                        'Trebuchet'           => '"Trebuchet MS", Verdana, sans-serif',
                        'Verdana'             => 'Verdana, Geneva, sans-serif',
                        'Inherit'             => 'inherit',
                    ),
                ),
                */
                array(
                    'type' => 'select-custom',
                    'vars' => '*-font-weight',
                    'options' => array(
                        'Normal'            => 'normal',
                        'Bold'              => 'bold',
                        'Lighter'           => 'lighter',
                        'Bolder'            => 'bolder',
                        '100 (Thin)'        => '100',
                        '200 (Extra Light)' => '200',
                        '300 (Light)'       => '300',
                        '400 (Normal)'      => '400',
                        '500 (Medium)'      => '500',
                        '600 (Semi Bold)'   => '600',
                        '700 (Bold)'        => '700',
                        '800 (Extra Bold)'  => '800',
                        '900 (Black)'       => '900',
                        'Inherit'           => 'inherit',
                    ),
                ),
                array(
                    'type' => 'select-custom',
                    'vars' => '*-font-style',
                    'options' => array(
                        'Normal'  => 'normal',
                        'Italic'  => 'italic',
                        'Inherit' => 'inherit',
                    ),
                ),
                array(
                    'type' => 'select-custom',
                    'vars' => '*-text-align',
                    'options' => array(
                        'Left'    => 'left',
                        'Right'   => 'right',
                        'Center'  => 'center',
                        'Justify' => 'justify',
                        'Inherit' => 'inherit',
                    ),
                ),
                array(
                    'type' => 'select-custom',
                    'vars' => '*-text-transform',
                    'options' => array(
                        'None'       => 'none',
                        'Lowercase'  => 'lowercase',
                        'Uppercase'  => 'uppercase',
                        'Capitalize' => 'capitalize',
                        'Inherit'    => 'inherit',
                    ),
                ),
                array(
                    'type' => 'select-custom',
                    'vars' => '*-text-decoration',
                    'options' => array(
                        'None'      => 'none',
                        'Underline' => 'underline',
                    ),
                ),
                array(
                    'type' => 'select-custom',
                    'vars' => '@inverse-global-color-mode',
                    'options' => array(
                        'Light'   => 'light',
                        'Dark'    => 'dark',
                        'None'    => 'none',
                    ),
                ),
                array(
                    'type' => 'select-custom',
                    'vars' => '@primary-global-color-mode',
                    'options' => array(
                        'Primary' => 'primary',
                        'None'    => 'none',
                    ),
                ),
                array(
                    'type' => 'select-custom',
                    'vars' => '*-color-mode',
                    'options' => array(
                        'Primary' => 'primary',
                        'Light'   => 'light',
                        'Dark'    => 'dark',
                        'None'    => 'none',
                    ),
                ),
                array(
                    'type' => 'select-custom',
                    'vars' => '*-border-mode',
                    'options' => array(
                        'Full'   => '',
                        'Top'    => '-top',
                        'Bottom' => '-bottom',
                        'Left'   => '-left',
                        'Right'  => '-right',
                    ),
                ),
                array(
                    'type' => 'select-custom',
                    'vars' => '*-position-mode',
                    'options' => array(
                        'Top'    => 'top',
                        'Bottom' => 'bottom',
                    ),
                ),
                array(
                    'type' => 'select-custom',
                    'vars' => array(
                        '*-nav-item-line-mode',
                        '*-nav-item-line-slide-mode',
                        '*-nav-item-line-active-mode',
                    ),
                    'options' => array(
                        'Enable'  => 'true',
                        'Disable' => 'false',
                    ),
                ),
                array(
                    'type' => 'select-custom',
                    'vars' => '*button-text-mode',
                    'options' => array(
                        'None'          => 'none',
                        'Line'          => 'line',
                        'Arrow'         => 'arrow',
                        'Em Dash'       => 'em-dash',
                        'Border Bottom' => 'border-bottom',
                    ),
                ),
                array(
                    'type' => 'select-custom',
                    'vars' => '*navbar-mode',
                    'options' => array(
                        'None'   => 'none',
                        'Border' => 'border',
                        'Frame'  => 'frame',
                    ),
                ),
                array(
                    'type' => 'checkbox',
                    'vars' => array(
                        '*-em-dash',
                        '*navbar-mode-border-vertical',
                        '*blockquote-icon',
                    ),
                    'attrs' => array(
                        'true-value' => 'true',
                    ),
                ),
                array(
                    'type' => 'text',
                    'vars' => '*',
                ),
            ),
        ),
    ),
);
